### PR TITLE
Use psycopg2cffi instead of psycopg2

### PR DESCRIPTION
**Pull request by charmander**
Compatible with PyPy and might resolve an elusive SystemError. `site.config.txt`s and `alembic.ini`s will have to be updated.

### CODE REVIEW

**Comment by weykent** [comment]
It is possible to use `psycopg2cffi.compat.register` instead of having to change the config. Does it matter if we never use the non-cffi version?

**Comment by charmander** [comment]
That feels like a bit of a hack.

**Comment by weykent** [comment]
I mean, yes, it is, but it saves having to find every use of `psycopg2` everywhere.

**Comment by charmander** [comment]
I’m pretty sure this covers all of the instances in weasyl itself now.

**Pull request merged**
