### PR TITLE
Use docker-compose for development

### PR DESCRIPTION
**Pull request by charmander**
I hope this makes getting set up less painful for everyone. Right now things are configured in a sort of minimal way, which means somewhat long rebuild times after every change, but it does support use of a remote Docker instance out of the box, so people can set up Docker in, for example, a local or remote VM.

Closes #60.

### CODE REVIEW

**Review by kfkitsune — APPROVED** [review]
Nearest I can ascertain, this works flawlessly. (Had a moment of confusion when my browser added ``https`` as the protocol, and it failed to work, but other than that, no readily visible snags in getting it working.)

🎉

**Comment by charmander** [comment]
Great to hear! \o/ Thanks for reviewing it.

**Comment by charmander** [comment]
Should I remove the Vagrant-based setup as part of this? I don’t think it works anymore.

**Comment by kfkitsune** [comment]
> 
> 
> Should I remove the Vagrant-based setup as part of this? I don’t think it works anymore.

Might as well; doesn't really make sense to maintain two distinct development environment toolkits, unless I am missing some non-obvious use case.

**Pull request merged**
